source $HOME/Source/terminal-config/vim/config/01.plugins.vim
source $HOME/Source/terminal-config/vim/config/02.init.vim
source $HOME/Source/terminal-config/vim/config/03.language_client.vim
source $HOME/Source/terminal-config/vim/config/04.plugin_config.vim
source $HOME/.config/nvim/config/05.coc_init.vim
